### PR TITLE
Relax blaze-html upper bound (Stackage 2.x support)

### PR DESCRIPTION
**Pull request by geraldus**
Sorry, I've forgot to create separate branch and it took ages to check everything is good within sandbox.

### CODE REVIEW

**Comment by pbrisbin** [comment]
Thanks, will test-compile and release

**Comment by pbrisbin** [comment]
Released as 0.9.4

**Comment by geraldus** [comment]
fine!

**Comment by nomeata** [comment]
geraldus, since you care about stackage compatibility, how about you add yesod-markdown to stackage, and serve as a proxy there. Pat Brisbin said he would not do it himself.

**Comment by geraldus** [comment]
> since you care about stackage compatibility
@nomeata, this was because I use `cabal.config` from Stackage with my current project, and `yesod-markdown` was project's dependency. Though I can add this to Stackage I've already switched to `markdown`; but likely I could use `yesod-markdown` in near future, in that case I'll add it to Stackage. Is it ok?

**Comment by nomeata** [comment]
Sure it's ok!

**Pull request merged**
